# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='File name')),
                ('from_date', models.DateField(verbose_name='Starting date in file')),
                ('to_date', models.DateField(verbose_name='Finishing date in file')),
                ('filesize', models.IntegerField(verbose_name='File Size')),
                ('is_public', models.BooleanField(verbose_name='Should the file be public')),
            ],
        ),
    ]
