# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfile',
            name='url',
            field=models.CharField(default=1, max_length=500, verbose_name='URL or location of the file'),
            preserve_default=False,
        ),
    ]
