# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-11 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_server', '0002_inputfile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfile',
            name='data_pending',
            field=models.BooleanField(default=True, verbose_name='Is there any pending data in the file?'),
        ),
        migrations.AlterField(
            model_name='inputfile',
            name='from_date',
            field=models.DateField(blank=True, null=True, verbose_name='Starting date in file'),
        ),
        migrations.AlterField(
            model_name='inputfile',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Should the file be public?'),
        ),
        migrations.AlterField(
            model_name='inputfile',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='Finishing date in file'),
        ),
    ]
