# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 02:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DaneUsers', '0002_auto_20160408_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdaneuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 27, 2, 46, 50, 97776, tzinfo=utc)),
        ),
    ]
