# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 02:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DaneUsers', '0003_auto_20160920_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdaneuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 27, 2, 57, 52, 187002, tzinfo=utc)),
        ),
    ]
