# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 22:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DaneUsers', '0004_auto_20160920_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdaneuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 10, 22, 54, 27, 445150, tzinfo=utc)),
        ),
    ]
